#!/bin/bash
echo "Basics"
echo "New terminal: Win + Enter"
echo "focus left: Win + j"   
echo "focus down: Win + k"   
echo "focus up: Win + l"   
echo "focus right: Win + ;"   
echo "focus parent: Win + a"   
echo "toggle focus mode: Win + Space"   
echo "Moving Windows"
echo "move Window left: Win + Shift + j"   
echo "move Window down: Win + Shift + k"   
echo "move Window up: Win + Shift + l"   
echo "move Window right: Win + Shift + ;"   
echo "Modifying windows"
echo "toggle fullscreen: Win + f"   
echo "split vertically: Win + v"   
echo "split horizontally: Win + h"   
echo "resize mode: Win + r"   
echo "Changing the container layout"
echo "default: Win + e "   
echo "stacking: Win + s"   
echo "tabbed: Win + w"   
echo "Floating"
echo "toggle floating: Win + Shift + Space"   
echo "drag floating: Win + Left click"
echo "Using workspaces"   
echo "switch to another workspace: Win + 0-9"   
echo "move a window to another workspace: Win + Shift + 0-9"
echo "Applications"
echo "open application launcher: Win + d"
echo "Kill window: Win + Shift + q"
echo "Restart/Exit"
echo "reload the .conf file: Win + Shift + c"
echo "restart i3: Win + Shift + r"
echo "exit i3: Win + Shift + e"   

